sudo: false

dist: xenial

cache: pip

language: python

notifications:
  email: false

python:
    - 2.7
    - 3.7

script:
    - pip install -v -e .
    - pip install mxnet --pre
    - pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
    - pip install coveralls
    - nosetests -s --with-coverage

after_success:
    - coveralls
