image: Visual Studio 2015
version: 1.0.{build}

environment:
    matrix:
        - PYTHON: C:\Python27-x64
        - PYTHON: C:\Python37-x64

build_script:
- cmd: >-

    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    pip install -v -e .

    pip install mxnet --pre

    if "%PYTHON%" == "C:\Python36-x64" (pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html)

    pip install python-coveralls nose

    call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64

    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

test_script:
- cmd: python -m nose -s --with-coverage
